# Generated by Django 4.2 on 2023-05-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('numero_tel', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('model', models.CharField(max_length=30)),
                ('type_carburant', models.CharField(max_length=30)),
                ('prix_location', models.IntegerField(default=0)),
                ('img_vehicule', models.ImageField(blank=True, null=True, upload_to='voitures')),
                ('disponibilite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deb_location', models.DateField()),
                ('fin_location', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.IntegerField(default=0)),
                ('date_payement', models.DateField()),
                ('reservation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='list.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('client', models.ManyToManyField(to='list.client')),
                ('voiture', models.ManyToManyField(to='list.voiture')),
            ],
        ),
    ]
