# Generated by Django 4.2 on 2023-05-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reserve',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='list.voiture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='reserve',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='list.reservation'),
            preserve_default=False,
        ),
    ]
