# Generated by Django 4.1.7 on 2023-05-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_remove_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_tel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
