# Generated by Django 4.1.7 on 2023-05-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='client',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='voiture',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.client'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='voiture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.voiture'),
        ),
    ]
