# Generated by Django 5.1.1 on 2024-10-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_remove_commentaire_client_alter_commentaire_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='prix_location',
            new_name='prix_location_hors_ville',
        ),
        migrations.AddField(
            model_name='reservation',
            name='avec_chauffeur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='prix_location_ville',
            field=models.IntegerField(default=0),
        ),
    ]
