# Generated by Django 5.1.1 on 2024-10-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_rename_prix_location_voiture_prix_location_hors_ville_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='lieu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
