# Generated by Django 5.1.1 on 2024-10-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_reservation_lieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='note',
        ),
    ]
