# Generated by Django 5.1.1 on 2024-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_remove_commentaire_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='detail_reservation',
            field=models.TextField(blank=True),
        ),
    ]
