# Generated by Django 5.1.1 on 2024-10-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_reservation_detail_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_facture', models.IntegerField(default=0)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('est_paye', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='list.reservation')),
            ],
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
