# Generated by Django 5.1.1 on 2024-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_facture_delete_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='region',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_facture',
            field=models.IntegerField(),
        ),
    ]
