# Generated by Django 5.1.1 on 2024-12-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_voiture_climatisation_voiture_nombre_siege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='prix_location_hors_ville',
            new_name='prix_location_hors_ville_chauffeur',
        ),
        migrations.RenameField(
            model_name='voiture',
            old_name='prix_location_ville',
            new_name='prix_location_hors_ville_sans_chauffeur',
        ),
        migrations.AddField(
            model_name='voiture',
            name='prix_location_ville_chauffeur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiture',
            name='prix_location_ville_sans_chauffeur',
            field=models.IntegerField(default=0),
        ),
    ]
