# Generated by Django 5.1.1 on 2025-02-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0017_rename_prix_location_hors_ville_voiture_prix_location_hors_ville_chauffeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant_facture',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
