# Generated by Django 5.1.1 on 2025-02-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_reservation_montant_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='tarif_A_B',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
