# Generated by Django 5.1.1 on 2025-04-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_voiture_tarif_a_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='boite',
            field=models.CharField(choices=[('Automatique', 'Automatique'), ('Manuelle', 'Manuelle')], default='Manuelle', max_length=15),
        ),
    ]
