# Generated by Django 5.1.1 on 2025-06-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0020_voiture_boite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='est_finalise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiture',
            name='immatriculation',
            field=models.CharField(default='TG-0000-AA', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_tel',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant_facture',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(blank=True, max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('disponible', models.BooleanField(default=True)),
                ('voiture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_entretien', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('cout', models.PositiveIntegerField(default=0)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.voiture')),
            ],
        ),
    ]
